### PR TITLE
Support minimum ABI stable SPM. Swift 5.0

### PR DESCRIPTION
**Pull request by muizidn**
As of there's no specific feature of Swift 5.1 required in the project, is it good to make EnumKit Package.swift declares on lowest but ABI stable Swift version which is Swift 5.0

### CODE REVIEW

**Comment by gringoireDM** [comment]
The new version only includes Combine extension, which is not required if you are on older Xcode version anyway, therefore it can be ignored. Is there some specific need for you to downgrade SPM to 5.0?

**Comment by muizidn** [comment]
I want to make it available in Linux and use it in my Swift 5.0 project (build for Mac under 10.15). Any suggestion?

**Comment by gringoireDM** [comment]
you can use the 1.0.0 version.

**Comment by muizidn** [comment]
Ah, yes. Ahaha. Thank you!

**Pull request closed without merging**
